JS=*.js
MD=*.md
JSON=*.json
TXT=COPYING
DEST=~/.local/share/gnome-shell/extensions/OverlayKeyBlocker@lexruee.ch


install:
	mkdir -p $(DEST)
	cp $(JS) $(JSON) $(MD) $(TXT) $(DEST)
	
uninstall:
	rm -rf $(DEST)
